# Generated by Django 4.2.4 on 2023-08-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_multi', models.BooleanField(default=True, verbose_name='Для нескольких человек')),
                ('is_men', models.BooleanField(default=True, verbose_name='Для музчины')),
                ('name', models.CharField(max_length=255, verbose_name='Для кого')),
            ],
            options={
                'verbose_name': 'Приглошения',
            },
        ),
    ]
